apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    app: {{ include "mychart.name" . }}
    chart: {{ include "mychart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mychart.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "mychart.name" . }}
        release: {{ .Release.Name }}
      annotations:
        {{- toYaml .Values.annotations | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ include "mychart.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            {{- range .Values.services }}
            {{- range .specs }}
            - containerPort: {{ .targetPort }}
              name: {{ .name }}
            {{- end }}
            {{- end }}
          env:
            {{- range $key, $value := .Values.global.environment }}
            - name: {{ $key }}
              value: "{{ $value | quote }}"
            {{- end }}
            {{- range $key, $value := .Values.environment }}
            - name: {{ $key }}
              value: "{{ $value | quote }}"
            {{- end }}
          {{- if .Values.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.liveness.path }}
              port: {{ .Values.liveness.port }}
            initialDelaySeconds: {{ .Values.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.liveness.periodSeconds }}
          {{- end }}
          {{- if .Values.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readiness.path }}
              port: {{ .Values.readiness.port }}
            initialDelaySeconds: {{ .Values.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.readiness.periodSeconds }}
            failureThreshold: {{ .Values.readiness.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- if and .Values.volumes.enabled .Values.volumes.pvc.enabled }}
      volumes:
        - name: pvc-storage
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.pvc.name }}
      {{- end }}
