apiVersion: v1
kind: Service
metadata:
  name: {{ (index .Values.services 0).name | default (include "mychart.fullname" .) }}
  labels:
    app: {{ include "mychart.name" . }}
spec:
  type: {{ (index .Values.services 0).type | default "ClusterIP" }}
  ports:
    {{- range (index .Values.services 0).specs }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    app: {{ include "mychart.name" . }}
    release: {{ .Release.Name }}
